version: "3.1"

services:
  sletmaster:
    container_name: sletmaster
    build:
      context: .
    command: poetry run uvicorn sletmaster.main:app --port 8000 --host 0.0.0.0 --debug --reload --workers 4
    ports:
      - 8000:8000
    volumes:
      - ./sletmaster:/app/sletmaster
      - ./pyproject.toml:/app/pyproject.toml
    env_file:
        - ./.env
    expose:
      - "5432"
    environment:
      DB_HOST: mongo
      DB_USER: root
      DB_PASS: example
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    volumes:
      - mongodata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/


volumes:
  mongodata:
